### ISSUE TITLE
What is the difference between your querystring and node build-in querystring

### ISSUE THREAD

**Issue by Froguard** [Gozala/querystring#18]
If I wanna use your qs, should I write code as this?
```js
var newQs = require('./node_modules/querystring');
````
And what is the difference between your querystring and node build-in querystring, a little confused

**Comment by mateuspv** [comment]
@Froguard this module seems have the same API of node build-in querystring, but it targets a web browser.

**Comment by Bertuzb** [comment]
how exactly does it target a browser? One can only tell by looking at the test platforms.

Anyway, for some reason, this module works in my Titanium project (js framework for apps) and the `query-string` does not

**Comment by mk-pmb** [comment]
> how exactly does it target a browser?

Usually that means it avoids using any Node.js feature that a browser wouldn't have.

**Comment by medikoo** [comment]
See proposed roadmap https://github.com/Gozala/querystring/issues/20 it's the intention for future versions
