### ISSUE TITLE
Incorrect deprecation message

### ISSUE THREAD

**Issue by hampuskraft** [Gozala/querystring#53]
Hi there,

I just want to inform you that the deprecation message for this package currently is "The".

![image](https://user-images.githubusercontent.com/24176136/125055680-c4274400-e0a7-11eb-9ab5-aeb72f3a2de0.png)

![image](https://user-images.githubusercontent.com/24176136/125055705-c8536180-e0a7-11eb-88c1-90e4b10b6fca.png)

Kind regards,
Hampus Kraft.

**Comment by hampuskraft** [comment]
cc @Gozala

**Comment by medikoo** [comment]
@hampuskraft Great thanks for reporting that. I've fixed this message
